//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace TaekReport.OlurFormu {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsOlurFormu")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsOlurFormu : global::System.Data.DataSet {
        
        private dtOlurFormuDataTable tabledtOlurFormu;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public dsOlurFormu() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected dsOlurFormu(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dtOlurFormu"] != null)) {
                    base.Tables.Add(new dtOlurFormuDataTable(ds.Tables["dtOlurFormu"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtOlurFormuDataTable dtOlurFormu {
            get {
                return this.tabledtOlurFormu;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsOlurFormu cln = ((dsOlurFormu)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dtOlurFormu"] != null)) {
                    base.Tables.Add(new dtOlurFormuDataTable(ds.Tables["dtOlurFormu"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledtOlurFormu = ((dtOlurFormuDataTable)(base.Tables["dtOlurFormu"]));
            if ((initTable == true)) {
                if ((this.tabledtOlurFormu != null)) {
                    this.tabledtOlurFormu.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsOlurFormu";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsOlurFormu.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledtOlurFormu = new dtOlurFormuDataTable();
            base.Tables.Add(this.tabledtOlurFormu);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializedtOlurFormu() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsOlurFormu ds = new dsOlurFormu();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void dtOlurFormuRowChangeEventHandler(object sender, dtOlurFormuRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtOlurFormuDataTable : global::System.Data.TypedTableBase<dtOlurFormuRow> {
            
            private global::System.Data.DataColumn columnCALISMANINADI;
            
            private global::System.Data.DataColumn columnCALISMANINAMACI;
            
            private global::System.Data.DataColumn columnUYGULAMA;
            
            private global::System.Data.DataColumn columnFTAOLASILIK;
            
            private global::System.Data.DataColumn columnZAMAN;
            
            private global::System.Data.DataColumn columnTAHMINIGONULLUSAYI;
            
            private global::System.Data.DataColumn columnMATERYALANALIZ;
            
            private global::System.Data.DataColumn columnBEKLENENLER;
            
            private global::System.Data.DataColumn columnYARARLAR;
            
            private global::System.Data.DataColumn columnSONAERDIRMEDURUMLARI;
            
            private global::System.Data.DataColumn columnZARARLAR;
            
            private global::System.Data.DataColumn columnKATILMAZISE;
            
            private global::System.Data.DataColumn columnALTERNATIFYONTEMLER;
            
            private global::System.Data.DataColumn columnUCRETODENECEKMI;
            
            private global::System.Data.DataColumn columnSORUMLUGUID;
            
            private global::System.Data.DataColumn columnKISIUCRETODEYECEKMI;
            
            private global::System.Data.DataColumn columnBILGILERINGIZLILIGI;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtOlurFormuDataTable() {
                this.TableName = "dtOlurFormu";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal dtOlurFormuDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected dtOlurFormuDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CALISMANINADIColumn {
                get {
                    return this.columnCALISMANINADI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CALISMANINAMACIColumn {
                get {
                    return this.columnCALISMANINAMACI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn UYGULAMAColumn {
                get {
                    return this.columnUYGULAMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn FTAOLASILIKColumn {
                get {
                    return this.columnFTAOLASILIK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ZAMANColumn {
                get {
                    return this.columnZAMAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn TAHMINIGONULLUSAYIColumn {
                get {
                    return this.columnTAHMINIGONULLUSAYI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn MATERYALANALIZColumn {
                get {
                    return this.columnMATERYALANALIZ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn BEKLENENLERColumn {
                get {
                    return this.columnBEKLENENLER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn YARARLARColumn {
                get {
                    return this.columnYARARLAR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn SONAERDIRMEDURUMLARIColumn {
                get {
                    return this.columnSONAERDIRMEDURUMLARI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ZARARLARColumn {
                get {
                    return this.columnZARARLAR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn KATILMAZISEColumn {
                get {
                    return this.columnKATILMAZISE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ALTERNATIFYONTEMLERColumn {
                get {
                    return this.columnALTERNATIFYONTEMLER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn UCRETODENECEKMIColumn {
                get {
                    return this.columnUCRETODENECEKMI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn SORUMLUGUIDColumn {
                get {
                    return this.columnSORUMLUGUID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn KISIUCRETODEYECEKMIColumn {
                get {
                    return this.columnKISIUCRETODEYECEKMI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn BILGILERINGIZLILIGIColumn {
                get {
                    return this.columnBILGILERINGIZLILIGI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtOlurFormuRow this[int index] {
                get {
                    return ((dtOlurFormuRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtOlurFormuRowChangeEventHandler dtOlurFormuRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtOlurFormuRowChangeEventHandler dtOlurFormuRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtOlurFormuRowChangeEventHandler dtOlurFormuRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtOlurFormuRowChangeEventHandler dtOlurFormuRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AdddtOlurFormuRow(dtOlurFormuRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtOlurFormuRow AdddtOlurFormuRow(
                        string CALISMANINADI, 
                        string CALISMANINAMACI, 
                        string UYGULAMA, 
                        string FTAOLASILIK, 
                        string ZAMAN, 
                        string TAHMINIGONULLUSAYI, 
                        string MATERYALANALIZ, 
                        string BEKLENENLER, 
                        string YARARLAR, 
                        string SONAERDIRMEDURUMLARI, 
                        string ZARARLAR, 
                        string KATILMAZISE, 
                        string ALTERNATIFYONTEMLER, 
                        string UCRETODENECEKMI, 
                        string SORUMLUGUID, 
                        string KISIUCRETODEYECEKMI, 
                        string BILGILERINGIZLILIGI) {
                dtOlurFormuRow rowdtOlurFormuRow = ((dtOlurFormuRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        CALISMANINADI,
                        CALISMANINAMACI,
                        UYGULAMA,
                        FTAOLASILIK,
                        ZAMAN,
                        TAHMINIGONULLUSAYI,
                        MATERYALANALIZ,
                        BEKLENENLER,
                        YARARLAR,
                        SONAERDIRMEDURUMLARI,
                        ZARARLAR,
                        KATILMAZISE,
                        ALTERNATIFYONTEMLER,
                        UCRETODENECEKMI,
                        SORUMLUGUID,
                        KISIUCRETODEYECEKMI,
                        BILGILERINGIZLILIGI};
                rowdtOlurFormuRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtOlurFormuRow);
                return rowdtOlurFormuRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dtOlurFormuDataTable cln = ((dtOlurFormuDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtOlurFormuDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnCALISMANINADI = base.Columns["CALISMANINADI"];
                this.columnCALISMANINAMACI = base.Columns["CALISMANINAMACI"];
                this.columnUYGULAMA = base.Columns["UYGULAMA"];
                this.columnFTAOLASILIK = base.Columns["FTAOLASILIK"];
                this.columnZAMAN = base.Columns["ZAMAN"];
                this.columnTAHMINIGONULLUSAYI = base.Columns["TAHMINIGONULLUSAYI"];
                this.columnMATERYALANALIZ = base.Columns["MATERYALANALIZ"];
                this.columnBEKLENENLER = base.Columns["BEKLENENLER"];
                this.columnYARARLAR = base.Columns["YARARLAR"];
                this.columnSONAERDIRMEDURUMLARI = base.Columns["SONAERDIRMEDURUMLARI"];
                this.columnZARARLAR = base.Columns["ZARARLAR"];
                this.columnKATILMAZISE = base.Columns["KATILMAZISE"];
                this.columnALTERNATIFYONTEMLER = base.Columns["ALTERNATIFYONTEMLER"];
                this.columnUCRETODENECEKMI = base.Columns["UCRETODENECEKMI"];
                this.columnSORUMLUGUID = base.Columns["SORUMLUGUID"];
                this.columnKISIUCRETODEYECEKMI = base.Columns["KISIUCRETODEYECEKMI"];
                this.columnBILGILERINGIZLILIGI = base.Columns["BILGILERINGIZLILIGI"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnCALISMANINADI = new global::System.Data.DataColumn("CALISMANINADI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCALISMANINADI);
                this.columnCALISMANINAMACI = new global::System.Data.DataColumn("CALISMANINAMACI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCALISMANINAMACI);
                this.columnUYGULAMA = new global::System.Data.DataColumn("UYGULAMA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUYGULAMA);
                this.columnFTAOLASILIK = new global::System.Data.DataColumn("FTAOLASILIK", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFTAOLASILIK);
                this.columnZAMAN = new global::System.Data.DataColumn("ZAMAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnZAMAN);
                this.columnTAHMINIGONULLUSAYI = new global::System.Data.DataColumn("TAHMINIGONULLUSAYI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTAHMINIGONULLUSAYI);
                this.columnMATERYALANALIZ = new global::System.Data.DataColumn("MATERYALANALIZ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMATERYALANALIZ);
                this.columnBEKLENENLER = new global::System.Data.DataColumn("BEKLENENLER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBEKLENENLER);
                this.columnYARARLAR = new global::System.Data.DataColumn("YARARLAR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYARARLAR);
                this.columnSONAERDIRMEDURUMLARI = new global::System.Data.DataColumn("SONAERDIRMEDURUMLARI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSONAERDIRMEDURUMLARI);
                this.columnZARARLAR = new global::System.Data.DataColumn("ZARARLAR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnZARARLAR);
                this.columnKATILMAZISE = new global::System.Data.DataColumn("KATILMAZISE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKATILMAZISE);
                this.columnALTERNATIFYONTEMLER = new global::System.Data.DataColumn("ALTERNATIFYONTEMLER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnALTERNATIFYONTEMLER);
                this.columnUCRETODENECEKMI = new global::System.Data.DataColumn("UCRETODENECEKMI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUCRETODENECEKMI);
                this.columnSORUMLUGUID = new global::System.Data.DataColumn("SORUMLUGUID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSORUMLUGUID);
                this.columnKISIUCRETODEYECEKMI = new global::System.Data.DataColumn("KISIUCRETODEYECEKMI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKISIUCRETODEYECEKMI);
                this.columnBILGILERINGIZLILIGI = new global::System.Data.DataColumn("BILGILERINGIZLILIGI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBILGILERINGIZLILIGI);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtOlurFormuRow NewdtOlurFormuRow() {
                return ((dtOlurFormuRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtOlurFormuRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dtOlurFormuRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtOlurFormuRowChanged != null)) {
                    this.dtOlurFormuRowChanged(this, new dtOlurFormuRowChangeEvent(((dtOlurFormuRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtOlurFormuRowChanging != null)) {
                    this.dtOlurFormuRowChanging(this, new dtOlurFormuRowChangeEvent(((dtOlurFormuRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtOlurFormuRowDeleted != null)) {
                    this.dtOlurFormuRowDeleted(this, new dtOlurFormuRowChangeEvent(((dtOlurFormuRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtOlurFormuRowDeleting != null)) {
                    this.dtOlurFormuRowDeleting(this, new dtOlurFormuRowChangeEvent(((dtOlurFormuRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemovedtOlurFormuRow(dtOlurFormuRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsOlurFormu ds = new dsOlurFormu();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtOlurFormuDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dtOlurFormuRow : global::System.Data.DataRow {
            
            private dtOlurFormuDataTable tabledtOlurFormu;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal dtOlurFormuRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtOlurFormu = ((dtOlurFormuDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CALISMANINADI {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.CALISMANINADIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'CALISMANINADI\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.CALISMANINADIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CALISMANINAMACI {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.CALISMANINAMACIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'CALISMANINAMACI\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.CALISMANINAMACIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string UYGULAMA {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.UYGULAMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'UYGULAMA\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.UYGULAMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string FTAOLASILIK {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.FTAOLASILIKColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'FTAOLASILIK\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.FTAOLASILIKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ZAMAN {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.ZAMANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'ZAMAN\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.ZAMANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string TAHMINIGONULLUSAYI {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.TAHMINIGONULLUSAYIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'TAHMINIGONULLUSAYI\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.TAHMINIGONULLUSAYIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string MATERYALANALIZ {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.MATERYALANALIZColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'MATERYALANALIZ\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.MATERYALANALIZColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string BEKLENENLER {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.BEKLENENLERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'BEKLENENLER\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.BEKLENENLERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string YARARLAR {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.YARARLARColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'YARARLAR\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.YARARLARColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string SONAERDIRMEDURUMLARI {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.SONAERDIRMEDURUMLARIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'SONAERDIRMEDURUMLARI\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.SONAERDIRMEDURUMLARIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ZARARLAR {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.ZARARLARColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'ZARARLAR\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.ZARARLARColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string KATILMAZISE {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.KATILMAZISEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'KATILMAZISE\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.KATILMAZISEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ALTERNATIFYONTEMLER {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.ALTERNATIFYONTEMLERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'ALTERNATIFYONTEMLER\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.ALTERNATIFYONTEMLERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string UCRETODENECEKMI {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.UCRETODENECEKMIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'UCRETODENECEKMI\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.UCRETODENECEKMIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string SORUMLUGUID {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.SORUMLUGUIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'SORUMLUGUID\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.SORUMLUGUIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string KISIUCRETODEYECEKMI {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.KISIUCRETODEYECEKMIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'KISIUCRETODEYECEKMI\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.KISIUCRETODEYECEKMIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string BILGILERINGIZLILIGI {
                get {
                    try {
                        return ((string)(this[this.tabledtOlurFormu.BILGILERINGIZLILIGIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'dtOlurFormu\' tablosundaki \'BILGILERINGIZLILIGI\' sütunun değeri DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtOlurFormu.BILGILERINGIZLILIGIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCALISMANINADINull() {
                return this.IsNull(this.tabledtOlurFormu.CALISMANINADIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCALISMANINADINull() {
                this[this.tabledtOlurFormu.CALISMANINADIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCALISMANINAMACINull() {
                return this.IsNull(this.tabledtOlurFormu.CALISMANINAMACIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCALISMANINAMACINull() {
                this[this.tabledtOlurFormu.CALISMANINAMACIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUYGULAMANull() {
                return this.IsNull(this.tabledtOlurFormu.UYGULAMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUYGULAMANull() {
                this[this.tabledtOlurFormu.UYGULAMAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsFTAOLASILIKNull() {
                return this.IsNull(this.tabledtOlurFormu.FTAOLASILIKColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetFTAOLASILIKNull() {
                this[this.tabledtOlurFormu.FTAOLASILIKColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsZAMANNull() {
                return this.IsNull(this.tabledtOlurFormu.ZAMANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetZAMANNull() {
                this[this.tabledtOlurFormu.ZAMANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsTAHMINIGONULLUSAYINull() {
                return this.IsNull(this.tabledtOlurFormu.TAHMINIGONULLUSAYIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetTAHMINIGONULLUSAYINull() {
                this[this.tabledtOlurFormu.TAHMINIGONULLUSAYIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsMATERYALANALIZNull() {
                return this.IsNull(this.tabledtOlurFormu.MATERYALANALIZColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetMATERYALANALIZNull() {
                this[this.tabledtOlurFormu.MATERYALANALIZColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsBEKLENENLERNull() {
                return this.IsNull(this.tabledtOlurFormu.BEKLENENLERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetBEKLENENLERNull() {
                this[this.tabledtOlurFormu.BEKLENENLERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsYARARLARNull() {
                return this.IsNull(this.tabledtOlurFormu.YARARLARColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetYARARLARNull() {
                this[this.tabledtOlurFormu.YARARLARColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSONAERDIRMEDURUMLARINull() {
                return this.IsNull(this.tabledtOlurFormu.SONAERDIRMEDURUMLARIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSONAERDIRMEDURUMLARINull() {
                this[this.tabledtOlurFormu.SONAERDIRMEDURUMLARIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsZARARLARNull() {
                return this.IsNull(this.tabledtOlurFormu.ZARARLARColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetZARARLARNull() {
                this[this.tabledtOlurFormu.ZARARLARColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsKATILMAZISENull() {
                return this.IsNull(this.tabledtOlurFormu.KATILMAZISEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetKATILMAZISENull() {
                this[this.tabledtOlurFormu.KATILMAZISEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsALTERNATIFYONTEMLERNull() {
                return this.IsNull(this.tabledtOlurFormu.ALTERNATIFYONTEMLERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetALTERNATIFYONTEMLERNull() {
                this[this.tabledtOlurFormu.ALTERNATIFYONTEMLERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUCRETODENECEKMINull() {
                return this.IsNull(this.tabledtOlurFormu.UCRETODENECEKMIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUCRETODENECEKMINull() {
                this[this.tabledtOlurFormu.UCRETODENECEKMIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSORUMLUGUIDNull() {
                return this.IsNull(this.tabledtOlurFormu.SORUMLUGUIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSORUMLUGUIDNull() {
                this[this.tabledtOlurFormu.SORUMLUGUIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsKISIUCRETODEYECEKMINull() {
                return this.IsNull(this.tabledtOlurFormu.KISIUCRETODEYECEKMIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetKISIUCRETODEYECEKMINull() {
                this[this.tabledtOlurFormu.KISIUCRETODEYECEKMIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsBILGILERINGIZLILIGINull() {
                return this.IsNull(this.tabledtOlurFormu.BILGILERINGIZLILIGIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetBILGILERINGIZLILIGINull() {
                this[this.tabledtOlurFormu.BILGILERINGIZLILIGIColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class dtOlurFormuRowChangeEvent : global::System.EventArgs {
            
            private dtOlurFormuRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtOlurFormuRowChangeEvent(dtOlurFormuRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtOlurFormuRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591